hypermap/aggregator/utils.py

Addition of functions to convert bounding boxes for layers not in geographic. Will need to add more projections that are non geographic and convert them

Solrprojectionissues

---

hypermap/aggregator/models.py

Getting of worldmap temporal_extent_start and end dates to be used when pushing to solr.

Worldmapdates

---

hypermap/dynasty/fixtures/initial_data.json

Addition of fixtures to add chinese dynasty dates for mining

Addition of chinese dynasty fixtures as a sample

---

hypermap/aggregator/solr.py
hypermap/aggregator/templates/aggregator/layer_detail.html
hypermap/aggregator/views.py

and the it to use the default hypermap id

Changes to show solr json endpoint on another tab

---

hypermap/aggregator/tests/test_worldmap.py
hypermap/aggregator/utils.py
hypermap/dynasty/tests.py
hypermap/dynasty/utils.py
hypermap/hypermap/context_processors.py

Adding another general catch except block. Will need to resolve the add_dates_to_metadata function later

Unicodeandtestfixes

---

hypermap/aggregator/tests/test_worldmap.py
hypermap/aggregator/utils.py
hypermap/dynasty/tests.py
hypermap/dynasty/utils.py
hypermap/hypermap/context_processors.py

Some changes to extra dates being processed and changing tests to return lists rather than single strings.

Unicodefixes

---

hypermap/aggregator/views.py

Celery fixes

---

hypermap/aggregator/elasticsearch_client.py

Reverses min/max objects without using a temp.

Improve readability of coordinate swap

---

hypermap/search_api/views.py

Fixing ElasticSearch Api
So far achieved you can search using the following params:
* q_text
* q_geo
* d_docs_limit
* d_docs_page

Edited Elasticsearch api

---

hypermap/search_api/views.py

* Fixing d_docs_page variable
* Getting better output looks similar to Solr Api 
* Adding unicode utf8 on dumping json
If you consider it's *Ok* , so you can accept this pull request

ElasticSearch API (WIP) 

---

hypermap/aggregator/migrations/0003_auto_20160812_2356.py
hypermap/aggregator/models.py
hypermap/aggregator/templates/aggregator/layer_detail.html
hypermap/aggregator/utils.py

This PR provides support for CSW-T Transaction operations in order to index (but not monitor) given resources.

support CSW-T push

---

hypermap/aggregator/admin.py
hypermap/aggregator/models.py
hypermap/aggregator/templates/aggregator/search.html
hypermap/aggregator/utils.py

https://github.com/cga-harvard/HHypermap/issues/154

provide more visibility to error messages while checks execution

---

hypermap/search/views.py

This PR implements pycsw on a per catalog basis in concert with pycsw [Repository Filters](http://docs.pycsw.org/en/latest/repofilters.html).

CSW for catalog slug

---

hypermap/__init__.py
hypermap/aggregator/templates/aggregator/base.html
hypermap/context_processors.py
setup.py

This PR enables display of the application name and version into webpages for verification/info at any given time.

display application name and version on UI

---

Makefile
docker-compose.override.yml
docker-compose.yml
hypermap/__init__.py
hypermap/aggregator/admin.py
hypermap/aggregator/elasticsearch_client.py
hypermap/aggregator/models.py
hypermap/aggregator/solr.py
hypermap/aggregator/tasks.py
hypermap/aggregator/templates/aggregator/base.html
hypermap/aggregator/templates/aggregator/celery_monitor.html
hypermap/aggregator/utils.py
hypermap/aggregator/views.py
hypermap/context_processors.py
hypermap/settings/default.py
setup.py

Registry temp

---

hypermap/aggregator/elasticsearch_client.py
hypermap/aggregator/tasks.py
hypermap/aggregator/views.py

Taking advantage of the cache, this commit applies indexing in elasticsearch with bulk.

Index in elasticsearch using bulk feature

---

hypermap/aggregator/utils.py

GeoNetwork OpenSource based CSW instances typically express links via `dc:URI`, not `dct:references`.  Though this is not part the CSW Record schema or Dublin Core, provide capability to parse and detect regardless given existing implementations.

CSW harvesting: process GeoNetwork-ish dc:URI links for detecting service links

---

Makefile
docker-compose.override.yml
hypermap/tests/mesonet.agron.iastate.edu.txt
hypermap/tests/test_end_to_end_selenium_firefox.py
requirements.txt

- implement e2e test with selenium and firefox with an initial user journey that begins on admin uploading an endpoint list and finishes using the app, checking services and layers checks, and asserting indexed layers in ES, use async celery tasks to emulate realistic environments.
- use docker compose image `selenium-firefox`
- `make test-endtoend-selenium-firefox` will be executed also with `make test`. make sure good usage of `END_TO_END_TEST_FLAGS`
- add selenium requirement

end2end tests to the startup user jourmey

---

Dockerfile
wait-for-postgres.sh

We started seeing problems where changes in the local requirements.txt
file would not be picked up on a new build.

Do not rely on docker-geonode anymore

---

hypermap/search/views.py

This PR re-implements #120, which looks like it got reverted.

enable CSW 3.0.0 support again

---

_docs/developers.md

Hello, this PR add some commands which puts the docker binaries under bin.

Update docker install document

---

hypermap/aggregator/models.py
hypermap/aggregator/utils.py
requirements.txt

[WIP] add OGC WMS 1.3.0 support (#216)

---

Makefile
_docs/admins.md
_docs/users.md
django.env
docker-compose.yml
hypermap/search/pycsw_plugin.py
hypermap/search/urls.py
hypermap/tests/test_csw.py
hypermap/tests/test_csw_transactions.py
requirements.txt

[WIP] CSW tests

---

_docs/developers.md

Added systemctl command to increase vm maparea

---

requirements.txt
setup.py

@ingenieroariel FYI not sure if changes are required to the Docker refs in https://github.com/cga-harvard/HHypermap/blob/master/Dockerfile#L1 as well.

bump pycsw

---

Makefile
README.md
hypermap/aggregator/count_srs.py
hypermap/aggregator/elasticsearch_client.py
hypermap/aggregator/models.py
hypermap/aggregator/tasks.py
hypermap/aggregator/templates/aggregator/layer_detail.html
hypermap/aggregator/utils.py

- minor formatting fixes
- fix make shell target
- add missing slash to template
- add keywords to search index
- make location true JSON property and consistent

miscellaneous fixes

---

hypermap/search/templates/search/csw-2.0.2-exception.xml
hypermap/search/views.py
hypermap/settings.py

@tomkralidis please review this

This fixes #244

---

hypermap/aggregator/admin.py
hypermap/aggregator/migrations/0011_flag_issues.py
hypermap/aggregator/models.py

There is no ID column in layer admin panel, which may be needed to flag layers which have some issues.

Add Issue and IssueType models to flag services/laysers which have some issues

---

Makefile
hypermap/aggregator/admin.py
hypermap/aggregator/models.py
hypermap/aggregator/populate_database.py
hypermap/aggregator/tasks.py
hypermap/aggregator/tests/test_metadata.py
hypermap/aggregator/tests/test_warper.py
hypermap/aggregator/tests/test_wms.py
hypermap/aggregator/tests/test_worldmap.py
hypermap/aggregator/utils.py
hypermap/dynasty/admin.py
hypermap/search_api/tests.py
hypermap/tests/test_csw.py

Fixes #271 and other failing tests. For now disabling pycsw tests until we fix them

Fixes #271 and other failing tests

---

hypermap/aggregator/templates/aggregator/layer_detail.html
hypermap/aggregator/templates/aggregator/service_detail.html
hypermap/search/pycsw_plugin.py

pycsw: fix UUID refs for services (#276)

---

Makefile
hypermap/search/pycsw_plugin.py
hypermap/tests/test_csw_transactions.py

Fix pycsw tests and re-enable them in make test (#273)

---

hypermap/aggregator/templates/aggregator/base.html
hypermap/static/js/hypermap.js

Provides autofocus capability on login, js file rename.

add autofocus and rename hypermap js file

---

hypermap/aggregator/templates/aggregator/layer_detail.html
hypermap/aggregator/templates/aggregator/service_detail.html
hypermap/static/js/hypermap.js

update some links as buttons

---

hypermap/aggregator/templates/aggregator/publish.html
hypermap/static/js/hypermap.js

This PR provides enhancements to the CSW-T Publish workflow in UI (processes/presents CSW-T response).

UI: add CSW-T handling

---

hypermap/aggregator/templates/aggregator/layer_checks.html
hypermap/aggregator/templates/aggregator/layer_detail.html
hypermap/aggregator/templates/aggregator/search.html
hypermap/aggregator/templates/aggregator/service_checks.html
hypermap/aggregator/templates/aggregator/service_detail.html
hypermap/aggregator/views.py
hypermap/settings.py
requirements.txt

Remove dj-pagination. Using django Paginator, which works much better with large datasets. Fixes #260

Remove dj-pagination. Using django Paginator, fixes #260

---

hypermap/aggregator/templates/aggregator/base.html
hypermap/aggregator/templates/aggregator/layer_detail.html
hypermap/aggregator/templates/aggregator/service_detail.html

- add `elementsetname=full` to CSW `GetRecordById` requests to provide full representation of metadata
- make search engine link label according to configuration

minor UI template updates

---

AUTHORS

Add the people listed in 'contributors', #243

add an AUTHORS file, issue #243

---

hypermap/aggregator/models.py

add local OGC:WMTS endpoint for a given layer (#328)

---

requirements.txt

Fixes [CVE-2018-18074](https://nvd.nist.gov/vuln/detail/CVE-2018-18074)

update requests version dependency

---

hypermap/aggregator/management/commands/delete_orphaned_thumbs.py
hypermap/aggregator/models.py
hypermap/aggregator/solr.py
hypermap/search/pycsw_plugin.py
requirements.txt

This PR addresses the following:
- https://nvd.nist.gov/vuln/detail/CVE-2019-11324
- https://nvd.nist.gov/vuln/detail/CVE-2018-20060
- https://nvd.nist.gov/vuln/detail/CVE-2017-18342d

update urllib3 and PyYAML deps

---

requirements.txt

Addreses:
- https://nvd.nist.gov/vuln/detail/CVE-2016-9189
- https://nvd.nist.gov/vuln/detail/CVE-2016-9190

update pillow dependency
